### ISSUE TITLE
Maps not working on public website

### ISSUE THREAD

**Issue by schuyler1d** [ccnmtl/maap#1]
MAAP came up in conversation and I decided to visit an old project and was sad that the maps don't seem to be loading anymore, e.g. here:
http://maap.columbia.edu/place/then.html

## Steps to 'reinitialize' the environment as-is

1. Go to http://maap.columbia.edu/place/then.html
2. Open the browser developer console
3. Go to this url in a separate tab: `view-source:http://maap.columbia.edu/place/maps.html`
4. Copy the javascript part entirely, excepting the prefix/suffix `<html><body><p>`
5. Paste the loadMaps call you copied into the developer console (in step 2)
6. Paste and run `initLoadThumbsAfterLoad();initMaapPanZoomForm()` in the developer console

That should prove that there is finite work to get MAAP (mostly) working again.

## Ideas to fix it

* It's possible that just making http://maap.columbia.edu/place/maps.html return pure javascript without the html wrapping (as it's cited in a `<script src=""` and with Content-Type: text/javascript or application/javascript.  The rest of the functions are likely depending on this to be called and loaded before they are.
** Alternatively if this is all served statically now, maybe just rename `maap.html` to `maap.html.js` and replace references in the static html files with the new name.
* If that is not enough, you could dump a palliative `<script>initLoadThumbsAfterLoad();initMaapPanZoomForm()</script>` at the bottom, maybe wrapped with a dumb setTimeout in order function with several seconds -- this would be hacky, but allow one to restore functionality without interrogating 

Much love, and miss CTL! /sky

**Comment by nbuonin** [comment]
@schuyler1d Thanks for the bug report!

The current site is being served statically by CUIT. There's a server migration in progress right now which requires that all the links be relative to the site root. I wrote a script to parse the site's html files and update the links. During that rewrite, the javascript got wrapped by Beautiful Soup and blew everything up. In any case, as much as I love the concept of palliative javascript, the fix was to delete the wrapping tags. The maps should be back now.

All best, Nick
